---
abstract: 'Safe compile-time module loading from a variable'
author:
  - 'Joel Berger <joel.a.berger@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-UseFrom
requires:
  Carp: 0
  Devel::Declare: 0
  ExtUtils::Installed: 0
  Module::CoreList: 0
  Scalar::Util: 0
  perl: v5.8.1
  strict: 0
  version: 0.77
  warnings: 0
version: 0.03
